format_version: 10
pipelines:
  master-ami:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/PrakharDevOpsLearning/Golden-AMI.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:f4ovgEOXsjAAp61j7h2fJQ==:kgBExEvigsJ/x3jp7LV65fz9OU/9GbFyMF8RBsa+NUw=

    stages:
      - CREATE:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init"], run_if: passed}
                - exec: {command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed}

      - DELETE:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init"], run_if: passed}
                - exec: {command: terraform, arguments: [ "state", "rm", "aws_ami_from_instance.ami" ], run_if: passed}     # to remove the state of ami image so that pipeline will not destroy image along with resource (instance)
                - exec: {command: terraform, arguments: [ "destroy", "-auto-approve" ], run_if: passed}